---
title: "Literature Reviews"
subtitle: "Exploring the Applications of Linear Mixed Models in Sleep Health and Lifestyle "
author: "Autumn Clark, Alex Ottley"
date: today
format:
  html: default
bibliography: references.bib
self-contained: true
execute: {}
editor: {}
---
## Autumn's Literature Review

This article provides an in-depth guide on using the lme4 package for fitting linear mixed-effects models in R. Bates discusses the theoretical foundations of mixed-effects models, including fixed and random effects, and shows how to specify and fit these models using the lmer function. The article includes examples and code snippets to illustrate model fitting, interpretation of results, and considerations for model selection and diagnostics. This resource will be valuable for our project by helping us apply mixed-effects modeling techniques in our analyses. [@bates2005fitting]

In full transparency, I was not able to finish reading this article/chapter as it is quite lengthy but the second article/chapter I started reading was Chapter 13 "Linear and Generalized Linear Mixed Models" by Benjamin M. Bolker. From what I've read so far, Bolker provides a very detailed exploration of generalized linear mixed models (GLMM), which combine the characteristics of GLMs and mixed models to deal with a wide range of response variables and grouped data. He discusses the importance of understanding fixed and random effects. He provided several ecological examples (case studies) that included some sort of grouped data that required mixed models. [@bolker2015linear]

This article discusses a study comparing different models of genetic analysis of feather scores in laying hens, with a focus on the back and neck of these hens at ages 45 and 70 weeks. Feather pecking, feather damage, and mortality are important health and efficiency traits in poultry. Genetic analysis of feather scores can help breed hens with better feather quality reducing feather damage and pecking. This study investigates how genetic parameters can be estimated from sib-group (a group of people/animals who share a common ancestor) data, considering both direct and indirect genetic influences. [@osorio2025comparison]
 
This study develops a hierarchical modeling approach to identify the "bad actors" in complex metal mixtures that could pose a risk of behavioral toxicity. The researchers used 92 drinking water samples from Maine and New Hampshire which contained multiple metal elements. The study used larval zebrafish to conduct a behavioral assay. This is used for screening large numbers of samples in a high throughput manner, which is a process that can handle a large volume of data or samples very quickly and efficiently. [@dilrukshi2024determining]

The article cited above discusses the use of the generalized linear mixed model (GLMM) framework for addressing overdispersion, correlated errors, shrinkage estimation, and smoothing in regression. GLMMs assume conditionally independent observations given random effects, with means linked to a predictor function and variances specified through a variance function. Random effects follow a normal distribution with unknown variance components. For time series, spatial aggregation, and smoothing problems, dispersion is modeled using a rank-deficient inverse covariance matrix. The estimation process involves approximating marginal quasi-likelihood using Laplace’s method, leading to penalized quasi-likelihood (PQL) for fixed effects and pseudo-likelihood for variance components. Through case studies, the authors demonstrate PQL's utility in hierarchical models. Applications include over dispersion in seed germination rates, longitudinal epilepsy studies, spatial clustering of lip cancer rates, and salamander mating experiments.[@breslow1993approximate] 

This paper explores how generalized linear mixed models (GLMMs) can be used to analyze ecological community dynamics by fitting species abundance distributions. Population dynamic models include key ecological parameters such as environmental noise, demographic variance, long-term growth rate, and density regulation strength, which are crucial for understanding changes in species communities. However, integrating these parameters into community models is complex. The authors propose using intercept-only GLMMs with different random effects to capture species-specific and general responses to environmental stochasticity, spatial variation, and differences in growth rate and carrying capacity. The method is applied to fish and bat communities, demonstrating the estimation of covariance and population dynamic parameters along with their uncertainties. The findings highlight species heterogeneity as the primary driver of spatial and temporal community similarity in both case studies. [@solbu2022analyzing]

-----------------------------------------------------------

## Alex's Literature Review

In cardiovascular research, Gonçalves et al. (2005) highlighted the efficiency of LMMs over ANOVA in analyzing heart rate and coronary-perfused pressure data in transgenic mice. Their study emphasized how LMMs provide a robust and sensitive approach to assessing experimental effects.

Matsumoto, Takeshi, et al. "Association between sleep disturbance and nocturnal blood pressure profiles by a linear mixed model analysis: the Nagahama study." Sleep Medicine 61 (2019): 104-109. https://doi.org/10.1093/ejcts/ezac429 Abnormal nocturnal blood pressure (BP) profiles have been linked to an increased risk of cardiovascular events (Kario, 2008). Sleep disturbances, including sleep-disordered breathing (SDB), sleep fragmentation, and reduced sleep efficiency, have been identified as potential contributors to these abnormal BP patterns (Mano et al., 2021). Research has shown that lower sleep efficiency is associated with a diminished nocturnal BP dip and higher sleep BP levels (Kario et al., 2001). Moreover, nocturnal urination, which often results from sleep disturbance, was also identified as a significant determinant of poor BP profiles (Miki et al., 2022). A key advantage of the study design in understanding these relationships was the use of Linear Mixed Models (LMMs), which allowed for the analysis of multi-day measurements and helped account for individual variations in both sleep patterns and blood pressure levels (Mano et al., 2021). By incorporating random effects, LMMs effectively modeled the variability between participants while controlling for day-to-day fluctuations, thus providing more accurate estimates of the associations between sleep and blood pressure (Kario et al., 2001). These statistical models are particularly beneficial in longitudinal and repeated-measure studies, as they capture individual differences and offer insights into complex interactions over time. The findings from LMMs confirmed that sleep efficiency independently influenced nocturnal BP profiles. This suggests that improving sleep quality could help regulate circadian blood pressure rhythms and reduce the risk of hypertension-related cardiovascular events. Employing these statistical methods ensures that the data analysis is reflective of the real-world irregularities of sleep and BP measurements.

Edwards & Simpson (2014) used LMMs by incorporating orthonormal polynomials to analyze 24-hour ambulatory blood pressure data. Their methodology enhanced visualization and provided medical experts with clearer insights into blood pressure variations over time.

Wang, Xu, et al. "Statistical primer: an introduction to the application of linear mixed-effects models in cardiothoracic surgery outcomes research—a case study using homograft pulmonary valve replacement data." European Journal of Cardio-Thoracic Surgery 62.4 (2022): ezac429. The study of cardiothoracic surgery outcomes has increasingly relied on big datasets that include both short-term and long-term outcomes as well as repeated measurements over time. These datasets provide opportunities for more advanced statistical methods such as linear mixed models (LMMs). LMMs are particularly beneficial for repeated measurements because they account for the dependence of these measurements within individual patients. Traditional linear regression models aren’t as efficient because they assume that measurements are independent, which is a violation when studying longitudinal data (Laird & Ware, 1982). Survival analysis has limitations in modeling dynamic outcomes like valve function, as it focuses on discrete events, ignoring the continuous evolution of patient conditions (Hosmer & Lemeshow, 2000).
The Erasmus MC dataset used in this article, includes serial echocardiographic measurements of the RVOT peak gradient in 623 patients who underwent pulmonary valve replacement (PVR) between 1986 and 2017. The dataset consisted of 5111 repeated measurements, with a mean follow-up of 11.46 years. This setup makes it an ideal case for illustrating the advantages of LMMs over simpler models. LMMs consist of two key parts: the random-effects part, which accounts for the correlation between repeated measurements within a patient, and the fixed-effects part, which explains the overall effect of age, sex, and treatment procedures (Pinheiro & Bates, 2000). 
One of the primary strengths of LMMs is their ability to deal with unbalanced data, which is common in longitudinal studies where patients may have a different number of measurements, or measurements are taken at uneven intervals. This differs with generalized estimating equations and analysis of variance, which are less effective in handling this type of data (Diggle et al., 2002). The LMM approach also allows for more valid estimates of patient-specific outcomes and population-level trends. This is especially valuable in cardiothoracic surgery as outcomes like valve function evolve over time and vary by individual patient characteristics.
LMMs provide flexibility when handling missing data which is a common issue in longitudinal studies (Rubin, 1987). In the current study, missing data were assumed to be missing at random, and imputation was used to create five complete datasets. The authors also compare LMMs with traditional approaches such as linear regression and time-to-event analysis, emphasizing the superiority of LMMs in this context. While survival analysis focuses on events at specific time points, LMMs can track continuous changes in outcomes over time, providing a more complete picture of a patient's data (Gould, 2013). Additionally, effect plots are encouraged as a way to visualize the complex interactions in the data, offering key insights into how outcomes evolve over time. Overall, linear mixed models are crucial in modeling repeated measurements in cardiothoracic surgery outcomes research, offering more valid and flexible estimates than traditional models. These models allow for the capture of both individual patient trajectories and population-level trends, handling missing data, multicollinearity, and unbalanced data with ease, and providing tools for clinicians to improve decision-making based on evolving patient outcomes.
